class TagsConstants:
    SUBCATEGORY_GENRE = "Genre"
    SUBCATEGORY_TOPICS = "Topics"
    SUBCATEGORY_BEHAVIORS = "Behaviors"
    SUBCATEGORY_NEEDS = "Needs"

    SUBCATEGORY_BEHAVIORS_ID = 4
    SUBCATEGORY_GENRE_ID = 21
    SUBCATEGORY_TOPICS_ID = 43
    SUBCATEGORY_NEEDS_ID = 27
    SUBCATEGORY_CORE_ID = 10
    SUBCATEGORY_ACTIVITIES_ID = 1
    SUBCATEGORY_PLATFORMS_ID = 29
    SUBCATEGORY_SOCIALS_ID = 39
    SUBCATEGORY_HOBBIES_ID = 22
    SUBCATEGORY_MOVIES_ID = 25
    SUBCATEGORY_ENTITIES_ID = 14
    SUBCATEGORY_ERAS_ID = 16
    SUBCATEGORY_ENVIRONMENT_ID = 15
    SUBCATEGORY_ROLES_ID = 37
    SUBCATEGORY_DOMAINS_ID = 12
    SUBCATEGORY_FOCUS_ID = 18
    SUBCATEGORY_MULTIPLAYER_ID = 26
    SUBCATEGORY_COMPLEXITY_ID = 6

    BEHAVIOR_EXPLORE = 522
    BEHAVIOR_UTILIZE = 519
    BEHAVIOR_IMPROVISE = 521
    BEHAVIOR_PLAN = 164
    BEHAVIOR_DESTROY = 173
    BEHAVIOR_CULTIVATE = 520
    BEHAVIOR_CHALLENGE = 525
    BEHAVIOR_BOND = 524
    BEHAVIOR_EXPRESS = 168
    BEHAVIOR_IMMERSE = 523

    TAG_TOPICS_REALITY = 234
    TAG_TOPICS_FANTASY = 233
    TAG_GENRE_SIMULATION = 28
    TAG_GENRE_STORY = 25

    PLATFORM_MOBILE = 1
    PLATFORM_PC = 2

    MONETIZATION_FREE = 526
    MONETIZATION_PREMIUM = 527
    MONETIZATION_SUBSCRIPTION = 528
    MONETIZATION_IAP = 529
    MONETIZATION_ADS = 530
    MONETIZATION_BLOCKCHAIN = 531

    ALLOWED_RANKED_SUBCATEGORIES = [SUBCATEGORY_GENRE_ID, SUBCATEGORY_TOPICS_ID]

    TAG_RANK_NONE = 0
    TAG_RANK_PRIMARY = 1
    TAG_RANK_SECONDARY = 2
    TAG_RANK_TERTIARY = 3

    ALLOWED_TAG_RANKS = [TAG_RANK_NONE, TAG_RANK_PRIMARY, TAG_RANK_SECONDARY, TAG_RANK_TERTIARY]


